package eu.arrowhead.common.database.repository;

import eu.arrowhead.common.database.entity.ChoreographerActionStepServiceDefinitionConnection;
import org.springframework.stereotype.Repository;

@Repository
public interface ChoreographerActionStepServiceDefinitionConnectionRepository extends RefreshableRepository<ChoreographerActionStepServiceDefinitionConnection,Long> {
}