package eu.arrowhead.common.database.repository;

public interface ChoreographerActionStepServiceDefinitionConnectionRepository extends RefreshableRepository<ChoreographerActionStepServiceDefinitionConnectionRepository, Long> {
}
