package eu.arrowhead.common.dto.internal;

public enum QoSMeasurementAttribute {
	MIN_RESPONSE_TIME, MAX_RESPONSE_TIME, MEAN_RESPONSE_TIME_WITH_TIMEOUT, MEAN_RESPONSE_TIME_WITHOUT_TIMEOUT, JITTER_WITH_TIMEOUT, JITTER_WITHOUT_TIMEOUT, LOST_PER_MEASUREMENT_PERCENT;
}
