package eu.arrowhead.common.core;

import eu.arrowhead.common.Utilities;
import org.springframework.util.Assert;

import static eu.arrowhead.common.CommonConstants.*;

public enum CoreSystemService {

    //=================================================================================================
    // elements

    // Authorization services
    AUTH_CONTROL_INTRA_SERVICE(CORE_SERVICE_AUTH_CONTROL_INTRA, AUTHORIZATION_URI + OP_AUTH_INTRA_CHECK_URI),
    AUTH_CONTROL_INTER_SERVICE(CORE_SERVICE_AUTH_CONTROL_INTER, AUTHORIZATION_URI + OP_AUTH_INTER_CHECK_URI),
    AUTH_TOKEN_GENERATION_SERVICE(CORE_SERVICE_AUTH_TOKEN_GENERATION, AUTHORIZATION_URI + OP_AUTH_TOKEN_URI),
    AUTH_PUBLIC_KEY_SERVICE(CORE_SERVICE_AUTH_PUBLIC_KEY, AUTHORIZATION_URI + OP_AUTH_KEY_URI),
    AUTH_CONTROL_SUBSCRIPTION_SERVICE(CORE_SERVICE_AUTH_CONTROL_SUBSCRIPTION, AUTHORIZATION_URI + OP_AUTH_SUBSCRIPTION_CHECK_URI),

    // Orchestrator services
    ORCHESTRATION_SERVICE(CORE_SERVICE_ORCH_PROCESS,
            ORCHESTRATOR_URI + OP_ORCH_PROCESS),

    // Gatekeeper services
    GATEKEEPER_GLOBAL_SERVICE_DISCOVERY(CORE_SERVICE_GATEKEEPER_GSD, GATEKEEPER_URI + OP_GATEKEEPER_GSD_SERVICE),
    GATEKEEPER_INTER_CLOUD_NEGOTIATION(CORE_SERVICE_GATEKEEPER_ICN, GATEKEEPER_URI + OP_GATEKEEPER_ICN_SERVICE),

    // Gateway services
    GATEWAY_PUBLIC_KEY_SERVICE(CORE_SERVICE_GATEWAY_PUBLIC_KEY, GATEWAY_URI + OP_GATEWAY_KEY_URI),
    GATEWAY_PROVIDER_SERVICE(CORE_SERVICE_GATEWAY_CONNECT_PROVIDER, GATEWAY_URI + OP_GATEWAY_CONNECT_PROVIDER_URI),
    GATEWAY_CONSUMER_SERVICE(CORE_SERVICE_GATEWAY_CONNECT_CONSUMER, GATEWAY_URI + OP_GATEWAY_CONNECT_CONSUMER_URI),

    // Eventhandler services
    EVENT_PUBLISH_SERVICE(CORE_SERVICE_EVENT_HANDLER_PUBLISH, EVENT_HANDLER_URI + OP_EVENT_HANDLER_PUBLISH),
    EVENT_SUBSCRIBE_SERVICE(CORE_SERVICE_EVENT_HANDLER_SUBSCRIBE, EVENT_HANDLER_URI + OP_EVENT_HANDLER_SUBSCRIBE),
    EVENT_UNSUBSCRIBE_SERVICE(CORE_SERVICE_EVENT_HANDLER_UNSUBSCRIBE, EVENT_HANDLER_URI + OP_EVENT_HANDLER_UNSUBSCRIBE),
    EVENT_PUBLISH_AUTH_UPDATE_SERVICE(CORE_SERVICE_EVENT_HANDLER_PUBLISH_AUTH_UPDATE, EVENT_HANDLER_URI + OP_EVENT_HANDLER_PUBLISH_AUTH_UPDATE),

	// CA services
	CERTIFICATE_AUTHORITY_SIGN_SERVICE(CORE_SERVICE_CERTIFICATE_AUTHORITY_SIGN, CERTIFICATE_AUTHRORITY_URI + OP_CA_SIGN_CERTIFICATE_URI),
	// QoS Monitor services
	QOS_MONITOR_PING_MEASUREMENT_SERVICE(CORE_SERVICE_QOS_MONITOR_PING_MEASUREMENT,
            QOS_MONITOR_URI + OP_QOS_MONITOR_PING_MEASUREMENT + OP_QOS_MONITOR_PING_MEASUREMENT_SUFFIX),

	// Onboarding services
    ONBOARDING_WITH_CERTIFICATE_AND_NAME_SERVICE(CORE_SERVICE_ONBOARDING_WITH_CERTIFICATE_AND_NAME, ONBOARDING_URI + OP_ONBOARDING_WITH_CERTIFICATE_AND_NAME),
    ONBOARDING_WITH_CERTIFICATE_AND_CSR_SERVICE(CORE_SERVICE_ONBOARDING_WITH_CERTIFICATE_AND_CSR, ONBOARDING_URI + OP_ONBOARDING_WITH_CERTIFICATE_AND_CSR),
    ONBOARDING_WITH_SHARED_SECRET_AND_NAME_SERVICE(CORE_SERVICE_ONBOARDING_WITH_SHARED_SECRET_AND_NAME, ONBOARDING_URI + OP_ONBOARDING_WITH_SHARED_SECRET_AND_NAME),
    ONBOARDING_WITH_SHARED_SECRET_AND_CSR_SERVICE(CORE_SERVICE_ONBOARDING_WITH_SHARED_SECRET_AND_CSR, ONBOARDING_URI + OP_ONBOARDING_WITH_SHARED_SECRET_AND_CSR),

    // Device Registry services
    DEVICE_REGISTRY_REGISTER_SERVICE(CORE_SERVICE_DEVICE_REGISTRY_REGISTER, DEVICE_REGISTRY_URI + OP_DEVICE_REGISTRY_REGISTER_URI),
    DEVICE_REGISTRY_UNREGISTER_SERVICE(CORE_SERVICE_DEVICE_REGISTRY_UNREGISTER, DEVICE_REGISTRY_URI + OP_DEVICE_REGISTRY_UNREGISTER_URI),
    DEVICE_REGISTRY_ONBOARDING_WITH_NAME_SERVICE(CORE_SERVICE_DEVICE_REGISTRY_ONBOARDING_WITH_NAME,
                                                 DEVICE_REGISTRY_URI + ONBOARDING_URI + OP_DEVICE_REGISTRY_ONBOARDING_WITH_NAME_URI),
    DEVICE_REGISTRY_ONBOARDING_WITH_CSR_SERVICE(CORE_SERVICE_DEVICE_REGISTRY_ONBOARDING_WITH_CSR,
                                                DEVICE_REGISTRY_URI + ONBOARDING_URI + OP_DEVICE_REGISTRY_ONBOARDING_WITH_CSR_URI),

    // System Registry services
    SYSTEM_REGISTRY_REGISTER_SERVICE(CORE_SERVICE_SYSTEM_REGISTRY_REGISTER, SYSTEM_REGISTRY_URI + OP_SYSTEM_REGISTRY_REGISTER_URI),
    SYSTEM_REGISTRY_UNREGISTER_SERVICE(CORE_SERVICE_SYSTEM_REGISTRY_UNREGISTER, SYSTEM_REGISTRY_URI + OP_SYSTEM_REGISTRY_UNREGISTER_URI),
    SYSTEM_REGISTRY_ONBOARDING_WITH_NAME_SERVICE(CORE_SERVICE_SYSTEM_REGISTRY_ONBOARDING_WITH_NAME,
                                                 SYSTEM_REGISTRY_URI + ONBOARDING_URI + OP_SYSTEM_REGISTRY_ONBOARDING_WITH_NAME_URI),
    SYSTEM_REGISTRY_ONBOARDING_WITH_CSR_SERVICE(CORE_SERVICE_SYSTEM_REGISTRY_ONBOARDING_WITH_CSR,
                                                SYSTEM_REGISTRY_URI + ONBOARDING_URI + OP_SYSTEM_REGISTRY_ONBOARDING_WITH_CSR_URI),

    // Service Registry services
    SERVICE_REGISTRY_REGISTER_SERVICE(CORE_SERVICE_SERVICE_REGISTRY_REGISTER, SERVICE_REGISTRY_URI + OP_SERVICE_REGISTRY_REGISTER_URI),
    SERVICE_REGISTRY_UNREGISTER_SERVICE(CORE_SERVICE_SERVICE_REGISTRY_UNREGISTER, SERVICE_REGISTRY_URI + OP_SERVICE_REGISTRY_UNREGISTER_URI),

    // Monitoring and Standard Verification Services
    MSCV_VERIFICATION_SERVICE(CORE_SERVICE_MSCV_VERIFICATION, MSCV_URI + OP_MSCV_EXECUTE_URI),
    MSCV_PUBLIC_KEY_SERVICE(CORE_SERVICE_MSCV_PUBLIC_KEY, MSCV_URI + OP_MSCV_PUBLIC_KEY_URI),
    MSCV_LOGIN_SERVICE(CORE_SERVICE_MSCV_LOGIN, MSCV_URI + OP_MSCV_LOGIN_URI);

    //TODO: additional services

    //=================================================================================================
    // members

    private final String serviceDefinition;
    private final String serviceUri;

    //=================================================================================================
    // methods

    //-------------------------------------------------------------------------------------------------
    public String getServiceDefinition() {
        return serviceDefinition;
    }

    public String getServiceUri() {
        return serviceUri;
    }


    //=================================================================================================
    // constructors

	//-------------------------------------------------------------------------------------------------
	private CoreSystemService(final String serviceDefinition, final String serviceUri) {
		Assert.isTrue(!Utilities.isEmpty(serviceDefinition), "Service definition is null or blank");
		Assert.isTrue(!Utilities.isEmpty(serviceUri), "Service URI is null or blank");
		
		this.serviceDefinition = serviceDefinition;
		this.serviceUri = serviceUri;
	}
}