FROM openjdk:11.0.12-jdk

RUN apt-get update && \
    apt-get install -y maven
	
WORKDIR /opt/arrowhead-temp

COPY ./ ./

RUN mvn -pl authorization -am -DskipTests clean install

RUN cd authorization/target && \
    mkdir /opt/arrowhead-authorization && \
	find ./ -name "*.jar" -print0 | xargs -0 cp -t "/opt/arrowhead-authorization/"

WORKDIR /opt/arrowhead-authorization

RUN rm -rf /opt/arrowhead-temp
RUN rm -rf /home/root/.m2

CMD find /opt/arrowhead-authorization/ -name "*.jar" -exec java -jar {} \;
