#!/bin/sh -e

. /usr/share/debconf/confmodule

if logname 2>/dev/null; then
    USER=$(logname)
    HOME=$(eval echo "~$USER")
else
    USER="root"
    HOME="/root"
fi

# Get installation type
db_input high arrowhead-core-common/db_host || true
db_input high arrowhead-core-common/mysql_password_gams || true

# Run dialogs
db_go || true

